baseURL = "/"
languageCode = "en-us"
title = "Radhika"
theme="ink"
googleAnalytics="UA-192160611-1"

[params]
    subtitle="Toshniwal"
    # Optional 64x64 avatar image.
    avatar = "https://i.imgur.com/D5wsoJN.gif"

    # Content types to disable Disqus on.
    disableDisqusTypes = ["page"]
    
    featherIconsCDN = true

    mode = "dark" # "dark" or "auto"
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/radhikatoshniwal"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/radhika-toshniwal-0287a7149/"



[taxonomies]
   tag = "tags"

